src/Entity/ContentInvoice.php
<?php

namespace App\Entity;

use App\Repository\ContentInvoiceRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContentInvoiceRepository::class)]
class ContentInvoice
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\ManyToOne(targetEntity: Invoice::class, inversedBy: 'contentInvoices')]
    #[ORM\JoinColumn(nullable: false)]
    private $invoice;

    #[ORM\Column(type: 'string', length: 255)]
    private $productName;

    #[ORM\Column(type: 'integer')]
    private $priceProduct;

    #[ORM\Column(type: 'string', length: 255)]
    private $imageProduct;

    #[ORM\Column(type: 'integer')]
    private $quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getInvoice(): ?Invoice
    {
        return $this->invoice;
    }

    public function setInvoice(?Invoice $invoice): self
    {
        $this->invoice = $invoice;

        return $this;
    }

    public function getProductName(): ?string
    {
        return $this->productName;
    }

    public function setProductName(string $productName): self
    {
        $this->productName = $productName;

        return $this;
    }

    public function getPriceProduct(): ?int
    {
        return $this->priceProduct;
    }

    public function setPriceProduct(int $priceProduct): self
    {
        $this->priceProduct = $priceProduct;

        return $this;
    }

    public function getImageProduct(): ?string
    {
        return $this->imageProduct;
    }

    public function setImageProduct(string $imageProduct): self
    {
        $this->imageProduct = $imageProduct;

        return $this;
    }  

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getTotal()
    {
        return $this->getPriceProduct() * $this->getQuantity();
    }
}

templates/customer/home.html.twig
{% extends "base.html.twig" %}

{% block description %}
	Découvrez un large choix de maquillage pas cher, bio, nouveauté, cosmétique, soin du visage et du corps

{% endblock %}


{% block title %}Maquillage _ Beauty-shop | Offres | Super prix

{% endblock %}

{% block body %}
	<div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
		<div class="carousel-indicators">
			<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
			<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
			<button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
		</div>
		<div id="#" class="carousel-inner height_carrousel">

			<div class="carousel-item active img">
				<img src="{{ asset('assets/img/img_slider3.jpg') }}" class="d-block w-100 imageCarousel" alt="ambiance salon d'estheticienne">

			</div>

			<div class="carousel-item img">
				<img src="{{ asset('assets/img/img_slider4.jpg') }}" class="d-block w-100 imageCarousel" alt="Soins visage">

			</div>

			<div class="carousel-item img">
				<img src="{{ asset('assets/img/img_slider5.jpg') }}" class="d-block w-100 imageCarousel" alt="Produit estheticienne">


			</div>
		</div>
		<button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
			<span class="carousel-control-prev-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Previous</span>
		</button>
		<button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
			<span class="carousel-control-next-icon" aria-hidden="true"></span>
			<span class="visually-hidden">Next</span>
		</button>
	</div>


	<section class="bg-light">

		<div
			class="container py-5">
			<!-- DEBUT LES CATEGORIES -->
			<div class="row">
				{% include "_messages_flash.html.twig" %}

				<div class="col-12">
					<h1 class="text-center">Les catégories</h1>
				</div>

				{% for category in categories %}

					<div class="col-sm-12 col-md-6 col-lg-4 mt-3">
						<div class="card">
							<img src="{{ category.imagePath }}" class="card-img-top imageCategory" alt="image_category">
							<div class="card-body">
								<h5 class="card-title">{{ category.name|u.truncate('25', '...',false) }}</h5>

								<a href="{{ path('boutique_product_show_by_category',{'id': category.id}) }}" class="btn btn-primary w-100">Découvrir</a>

							</div>
						</div>
					</div>
				{% endfor %}

			</div>
		</div>
	</section>
	<!-- FIN DES CATEGORIES -->

	<section>
		<!-- DEBUT LES NOUVEAUTES -->
		<div class="container py-5">


			<div class="row">

				<div class="col-12">
					<h2 class="text-center">Les nouveautés</h2>
				</div>

				{% for product in products %}

					<div class="col-sm-12 col-md-6 col-lg-4 mt-3">
						<div class="card">
							<a href="{{ path('boutique_product_detail',{'id': product.id} ) }}"></a>
							<img src="{{ product.imagePath }}" class="card-img-top imageCategory" alt="image_nouveaute">

							<div class="card-body">
								<h5 class="card-title">{{ product.name|u.truncate('25', '...',false) }}</h5>
								<p>{{ product.price | priceEuro }}</p>
								<a href="{{ path('boutique_product_detail',{'id': product.id} ) }}" class="btn btn-primary btn-sm mx-3">Descriptif</a>
								<a class="btn btn-success btn-sm mx-3" href="{{ path('cart_add',{ 'id' : product.id }) }}?routeToRedirect=home">
									<i class="fa-solid fa-cart-plus"></i>
								</a>


							</div>
						</div>
					</div>

				{% endfor %}
			</div>
		</div>
	</section>
	<!-- FIN DES NOUVEAUTES -->
{% endblock %}

templates/customer/panier.html.twig
{% extends "base.html.twig" %}

{% block title %}Panier = Beauty-shop
{% endblock %}

{% block body %}

	<section>
		<div class="container py-5">
			<div class="row">
				<div class="col-md-12 mb-3">
					<h1 class="text-center h130px">Mon panier</h1>
				</div>

				{% include "_messages_flash.html.twig" %}

				<div class="card-body mb-3">
					<div class="table-responsive">
						<table class="table tablePanier">
							<thead>
								<tr>
									<th scope="col">Produit</th>
									<th scope="col" class="text-center">Prix Unitaire</th>
									<th scope="col" class="text-center">Quantité</th>
									<th scope="col" class="text-center">Total</th>
								</tr>
							</thead>
							{% if detailProducts | length > 0 %}
								<tbody>
									{% for item in detailProducts %}
										<tr>
											<th>
												<div class="d-flex align-items-center">
													<img class="smallImgPurchase" src="{{ item.product.imagePath }}" alt="mon panier">
													<div class="d-flex flex-column align-items-center text-truncate px-2">
														<p>{{ item.product.name }}</p>
													</div>
												</div>
											</th>
											<td class="text-center">{{ item.product.price | priceEuro }}</td>
											<td class="center">
												<a class="btn btn-dark" href="{{ path('cart_decrement_product',{'id' : item.product.id }) }}">
													<i class="fas fa-minus-circle"></i>
												</a>
												<a class="btn">
													{{ item.qty }}</a>
												<a class="btn btn-dark" href="{{ path('cart_add',{'id' : item.product.id }) }}?routeToRedirect=panier">
													<i class="fas fa-plus-circle"></i>
												</a>
											</td>
											<td class="text-center">{{ item.total | priceEuro }}</td>
											<th>
												<a href="{{ path('cart_remove_product',{'id': item.product.id }) }}">
													<i class="fa-regular fa-circle-xmark textRaja mt-3 ms-5"></i>
												</a>
											</th>
										</tr>

									{% endfor %}
									<tr>
										<th colspan="2"></th>
										<th>
											<p class="text-center">
												<strong>Sous total</strong>
											</p>
										</th>
										<th>
											<p class="text-center">
												<strong>{{ totalPrixPanier | priceEuro}}</strong>
											</p>
										</th>
									</tr>
								</tbody>
							{% else %}
								<h2 class="h230px textGreen text-center">
									<strong>Oups !</strong>
									Votre panier est vide</h2>
							{% endif %}
						</table>
					</div>
				</div>
				<!-- FIN CARD-BODY-->
				<div class="col-12 d-flex justify-content-md-end">
					<a href="{{ path('home') }}" class="btn btn-dark btn-sm mx-3">Continuer mes achats</a>
					{% if detailProducts | length > 0 %}
						<a href="{{ path('boutique_commande_recap') }}" class="btn btn-success btn-sm ">Valider votre panier</a>
					{% endif %}

				</div>
			</div>
			<!-- FIN ROW-->
		</div>
		<!-- FIN CONTAINER -->
	</section>

{% endblock %}